# Generated by Django 4.2.7 on 2023-11-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='objetivo',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
