# Generated by Django 4.2.7 on 2023-11-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_tarea_objetivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='description',
            new_name='time',
        ),
    ]
