# Generated by Django 4.2.7 on 2023-11-20 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_rename_description_tarea_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarea',
            new_name='task',
        ),
    ]
